###################################################
# Copyright (C) IBM Corp. 2023 All Rights Reserved.
# Licensed under the Apache License v2.0
###################################################

---
- hosts: ssh_remove

  tasks:
    - name: Ansible lineinfile remove line example
      lineinfile:
        dest: /root/.ssh/authorized_keys
        line: "{{ ssh }}"
        state: absent
